version: '3'
services:
  app:
    container_name: crud-server
    environment:
      - PORT=3220
      - ENDPOINT=api/v1/
      - DB_SCHEMA=test
    build: .
    ports: 
      - 3220:8080 # Forward the exposed port 3220docker on the container to port 8080 on the host machine
    restart: on-failure
    depends_on:
      - postgres # This service depends on postgres. Start that first.
    networks:
      - crud-server

  postgres:
    image: postgres:11
    container_name: crud_db
    environment:
      - DB_HOST=localhost
      - DB_USER=localhost
      - DB_PASS=password
      - DB_NAME=crud-db
      - PG_MAXCONN=10
    ports:
      - '5432:5432'
    volumes:
      - ./database_postgers:/var/lib/postgresql/data
    networks:
      - crud-server


# Networks to be created to facilitate communication between containers
networks:
  crud-server:
